<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="30" started-at="2018-06-29T07:45:20Z" finished-at="2018-06-29T07:45:21Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="30" started-at="2018-06-29T07:45:20Z" finished-at="2018-06-29T07:45:21Z">
      <class name="readFile.ReadXMLFile">
        <test-method status="PASS" signature="readXMLFile()[pri:0, instance:readFile.ReadXMLFile@1dfb72a]" name="readXMLFile" is-config="true" duration-ms="21" started-at="2018-06-29T07:45:20Z" finished-at="2018-06-29T07:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readXMLFile -->
      </class> <!-- readFile.ReadXMLFile -->
      <class name="readFile.TestCases">
        <test-method status="PASS" signature="initialize()[pri:0, instance:readFile.TestCases@1c68925]" name="initialize" is-config="true" duration-ms="3" started-at="2018-06-29T07:45:20Z" finished-at="2018-06-29T07:45:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testCaseToValidateNodeName()[pri:0, instance:readFile.TestCases@1c68925]" name="testCaseToValidateNodeName" duration-ms="2" started-at="2018-06-29T07:45:21Z" finished-at="2018-06-29T07:45:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseToValidateNodeName -->
        <test-method status="FAIL" signature="testCaseToValidatePrice()[pri:0, instance:readFile.TestCases@1c68925]" name="testCaseToValidatePrice" duration-ms="0" started-at="2018-06-29T07:45:21Z" finished-at="2018-06-29T07:45:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [44.95] but found [44]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [44.95] but found [44]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at readFile.TestCases.testCaseToValidatePrice(TestCases.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseToValidatePrice -->
        <test-method status="PASS" signature="testCaseToValidationAuthorName()[pri:0, instance:readFile.TestCases@1c68925]" name="testCaseToValidationAuthorName" duration-ms="0" started-at="2018-06-29T07:45:21Z" finished-at="2018-06-29T07:45:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseToValidationAuthorName -->
      </class> <!-- readFile.TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
